/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Equipo1
 */
public class InfoContacto extends javax.swing.JFrame {

    /**
     * Creates new form InfoContacto
     */
    public InfoContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LbCorreo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LbEdad = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnAgregarContactos = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(370, 152));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);

        LbNombre.setText("usuario");
        getContentPane().add(LbNombre);

        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3);

        LbCorreo.setText("correo");
        getContentPane().add(LbCorreo);

        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5);

        LbEdad.setText("edad");
        getContentPane().add(LbEdad);

        BtnAgregar.setText("Agregar");
        getContentPane().add(BtnAgregar);

        BtnAgregarContactos.setText("Agregar sus contactos");
        getContentPane().add(BtnAgregarContactos);

        BtnCancelar.setText("Cancelar");
        getContentPane().add(BtnCancelar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAgregar() {
        return BtnAgregar;
    }

    public JButton getBtnAgregarContactos() {
        return BtnAgregarContactos;
    }

    public JButton getBtnCancelar() {
        return BtnCancelar;
    }

    public JLabel getLbCorreo() {
        return LbCorreo;
    }

    public JLabel getLbEdad() {
        return LbEdad;
    }

    public JLabel getLbNombre() {
        return LbNombre;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAgregarContactos;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LbCorreo;
    private javax.swing.JLabel LbEdad;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
