/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Equipo1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbCorreo = new javax.swing.JLabel();
        LbEdad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnListarTodos = new javax.swing.JMenuItem();
        BtnListarMisContactos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        BtnBuscarContactos = new javax.swing.JMenuItem();
        BtnEliminarContacto = new javax.swing.JMenuItem();
        BtnBorrarCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mi cuenta");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mini Facebook-FMAT");

        LbNombre.setText("miNombre");

        LbCorreo.setText("miCorreo");

        LbEdad.setText("miEdad");

        jMenu1.setText("Archivo");

        BtnListarTodos.setText("Listar todos");
        jMenu1.add(BtnListarTodos);

        BtnListarMisContactos.setText("Listar mis contactos");
        jMenu1.add(BtnListarMisContactos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        BtnBuscarContactos.setText("Buscar");
        jMenu2.add(BtnBuscarContactos);

        BtnEliminarContacto.setText("Eliminar contactos");
        jMenu2.add(BtnEliminarContacto);

        BtnBorrarCuenta.setText("Borrar mi cuenta");
        jMenu2.add(BtnBorrarCuenta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbNombre)
                                    .addComponent(LbCorreo)
                                    .addComponent(LbEdad)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbCorreo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbEdad)
                    .addComponent(jLabel4))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLbCorreo() {
        return LbCorreo;
    }

    public JLabel getLbEdad() {
        return LbEdad;
    }

    public JLabel getLbNombre() {
        return LbNombre;
    }

    public JMenuItem getBtnBuscarContactos() {
        return BtnBuscarContactos;
    }

    public JMenuItem getBtnListarMisContactos() {
        return BtnListarMisContactos;
    }

    public JMenuItem getBtnListarTodos() {
        return BtnListarTodos;
    }

    public JMenuItem getBtnBorrarCuenta() {
        return BtnBorrarCuenta;
    }

    public JMenuItem getBtnEliminarContacto() {
        return BtnEliminarContacto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnBorrarCuenta;
    private javax.swing.JMenuItem BtnBuscarContactos;
    private javax.swing.JMenuItem BtnEliminarContacto;
    private javax.swing.JMenuItem BtnListarMisContactos;
    private javax.swing.JMenuItem BtnListarTodos;
    private javax.swing.JLabel LbCorreo;
    private javax.swing.JLabel LbEdad;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
